name: Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PG_DATABASE: postgres
  PG_HOST: localhost
  PG_PORT: 5432
  PG_USER: postgres
  PG_PASSWORD: postgres

jobs:
  unit_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: ${{ env.PG_DATABASE }}
          POSTGRES_PASSWORD: ${{ env.PG_PASSWORD }}
          POSTGRES_USER: ${{ env.PG_USER }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Set up database
        run: |
          bundle exec rails db:create db:schema:load RAILS_ENV=test

      - name: Run tests
        run: bundle exec rails test
