name: Zeitwerk

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zeitwerk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Run Zeitwerk
      run: bundle exec rails zeitwerk:check